# Generated by Django 5.0.6 on 2025-02-22 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAT_NAME', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CONTACT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=30)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONE', models.BigIntegerField()),
                ('MESSAGES', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FEEDBACK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL_ID', models.EmailField(max_length=254)),
                ('RATING', models.CharField(max_length=30)),
                ('COMMENT', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registretion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONE', models.BigIntegerField()),
                ('PASSWORD', models.CharField(max_length=30)),
                ('ROLE', models.CharField(max_length=30)),
                ('STATUS', models.CharField(max_length=30)),
                ('ADDRESS', models.TextField()),
                ('GENDER', models.CharField(max_length=30)),
                ('DP', models.ImageField(null=True, upload_to='document')),
            ],
        ),
        migrations.CreateModel(
            name='EVENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_NAME', models.CharField(max_length=30)),
                ('E_IMAGE', models.ImageField(upload_to='document')),
                ('E_DATE', models.DateField()),
                ('E_TIME', models.TimeField()),
                ('E_ADDRESS_MAPLINK', models.TextField()),
                ('E_PRICE', models.IntegerField()),
                ('E_DESCRIPTION', models.TextField()),
                ('CATEGORY_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportLight.category')),
                ('SELLER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportLight.registretion')),
            ],
        ),
        migrations.CreateModel(
            name='CARDDETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=30)),
                ('CVV', models.IntegerField()),
                ('EXPDATE', models.DateField()),
                ('ACCOUNT_NO', models.BigIntegerField()),
                ('Registretion_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportLight.registretion')),
            ],
        ),
        migrations.CreateModel(
            name='BOOKING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCREENSHORT', models.ImageField(upload_to='document')),
                ('TIMESTAMP', models.TimeField()),
                ('EVENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportLight.event')),
                ('Registretion_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportLight.registretion')),
            ],
        ),
    ]
