# Generated by Django 5.0.6 on 2025-02-22 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportLight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='SELLER_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SportLight.registretion'),
        ),
    ]
