# Generated by Django 5.0.6 on 2025-03-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportLight', '0002_alter_event_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='SUBJECT',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
