# Generated by Django 5.0.6 on 2025-03-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportLight', '0003_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='E_IMAGE',
            field=models.ImageField(upload_to='event_images'),
        ),
    ]
