# Generated by Django 5.1.7 on 2025-04-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportLight', '0004_alter_event_e_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='E_ADDRESS_MAPLINK',
        ),
        migrations.AddField(
            model_name='event',
            name='E_URL',
            field=models.URLField(null=True),
        ),
    ]
