# Generated by Django 5.1.7 on 2025-04-21 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportLight', '0005_remove_event_e_address_maplink_event_e_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='SCREENSHORT',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='TIMESTAMP',
        ),
        migrations.AddField(
            model_name='booking',
            name='BOOKING_DATE',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='STATUS',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='TOTAL_AMOUNT',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PAYMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAYMENT_ID', models.CharField(max_length=100, unique=True)),
                ('ORDER_ID', models.CharField(max_length=100)),
                ('AMOUNT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PAYMENT_METHOD', models.CharField(max_length=50)),
                ('PAYMENT_STATUS', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('PAYMENT_DATE', models.DateTimeField(auto_now_add=True)),
                ('SIGNATURE', models.CharField(blank=True, max_length=200, null=True)),
                ('BOOKING_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportLight.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
