# Generated by Django 5.1.7 on 2025-04-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportLight', '0006_alter_booking_options_remove_booking_screenshort_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ORDER_ID',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='PAYMENT_METHOD',
        ),
    ]
